In [2]:
import pandas as pd

df = pd.read_excel("../raw/Book2.xlsx")
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,Unnamed: 13,Unnamed: 14,Daily Social Media,StressLevel
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0,NaN,NaN,7.9,2
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,NaN,NaN,1.9,8
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,NaN,NaN,1.3,2
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0,NaN,NaN,7.4,1
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0,NaN,NaN,4.7,3

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
 13  Unnamed: 13               0 non-null      float64
 14  Unnamed: 14               0 non-null      float64
 15  Daily Social Media        1200 non-null   float64
 16  StressLevel               1200 non-null   int64
dtypes: float64(8), int64(6), object(3)
memory usage: 159.5+ KB

In [4]:
df.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label', 'Unnamed: 13',
       'Unnamed: 14', 'Daily Social Media', 'StressLevel'],
      dtype='object')

In [5]:
#Missing values
df.isnull().sum()

age                            0
gender                         0
daily_social_media_hours       0
platform_usage                 0
sleep_hours                    0
screen_time_before_sleep       0
academic_performance           0
physical_activity              0
social_interaction_level       0
stress_level                   0
anxiety_level                  0
addiction_level                0
depression_label               0
Unnamed: 13                 1200
Unnamed: 14                 1200
Daily Social Media             0
StressLevel                    0
dtype: int64

In [6]:
df.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,Unnamed: 13,Unnamed: 14,Daily Social Media,StressLevel
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,0.0,0.0,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833,NaN,NaN,4.536667,5.445833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704,NaN,NaN,2.029599,2.903290
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000,NaN,NaN,1.000000,1.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000,NaN,NaN,2.800000,3.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000,NaN,NaN,4.500000,5.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000,NaN,NaN,6.300000,8.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000,NaN,NaN,8.000000,10.000000

In [8]:
df["platform_usage"].value_counts()

platform_usage
Instagram    411
TikTok       398
Both         391
Name: count, dtype: int64

In [9]:
df["gender"].value_counts()

gender
male      615
female    585
Name: count, dtype: int64

In [10]:
df = df.drop(columns=[
    "Unnamed: 13",
    "Unnamed: 14",
    "Daily Social Media",
    "StressLevel"
])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 122.0+ KB