In [1]:
import sys
print(sys.executable)

/home/brez/mypy/damod/.venv/bin/python

In [2]:
#load the dataset
import pandas as pd

df = pd.read_excel("../raw/Book2.xlsx")
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,Unnamed: 13,Unnamed: 14,Daily Social Media,StressLevel
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0,NaN,NaN,7.9,2
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,NaN,NaN,1.9,8
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,NaN,NaN,1.3,2
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0,NaN,NaN,7.4,1
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0,NaN,NaN,4.7,3

In [3]:
#inspect data set
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
 13  Unnamed: 13               0 non-null      float64
 14  Unnamed: 14               0 non-null      float64
 15  Daily Social Media        1200 non-null   float64
 16  StressLevel               1200 non-null   int64
dtypes: float64(8), int64(6), str(3)
memory usage: 177.9 KB

1200 rows

17 columns

In [4]:
df.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label', 'Unnamed: 13',
       'Unnamed: 14', 'Daily Social Media', 'StressLevel'],
      dtype='str')

In [5]:
#Missing values
df.isnull().sum()

age                            0
gender                         0
daily_social_media_hours       0
platform_usage                 0
sleep_hours                    0
screen_time_before_sleep       0
academic_performance           0
physical_activity              0
social_interaction_level       0
stress_level                   0
anxiety_level                  0
addiction_level                0
depression_label               0
Unnamed: 13                 1200
Unnamed: 14                 1200
Daily Social Media             0
StressLevel                    0
dtype: int64

Unnammed 13: 1200 missing

Unnammed 14: 1200 missing

In [6]:
df.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,Unnamed: 13,Unnamed: 14,Daily Social Media,StressLevel
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,0.0,0.0,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833,NaN,NaN,4.536667,5.445833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704,NaN,NaN,2.029599,2.903290
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000,NaN,NaN,1.000000,1.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000,NaN,NaN,2.800000,3.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000,NaN,NaN,4.500000,5.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000,NaN,NaN,6.300000,8.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000,NaN,NaN,8.000000,10.000000

Confirm duplicated columns

In [7]:
df = df.drop(columns=[
    "Unnamed: 13",
    "Unnamed: 14",
    "Daily Social Media",
    "StressLevel"
])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), str(3)
memory usage: 140.4 KB

trim duplicate

In [8]:
df['gender'].value_counts()

gender
male      615
female    585
Name: count, dtype: int64

In [9]:
df['platform_usage'].value_counts()

platform_usage
Instagram    411
TikTok       398
Both         391
Name: count, dtype: int64

In [10]:
df['social_interaction_level'].value_counts()

social_interaction_level
medium    416
low       415
high      369
Name: count, dtype: int64

In [11]:
df['depression_label'].value_counts()

depression_label
0    1169
1      31
Name: count, dtype: int64

In [12]:
df.nunique()

age                           7
gender                        2
daily_social_media_hours     71
platform_usage                3
sleep_hours                  51
screen_time_before_sleep     26
academic_performance        201
physical_activity            21
social_interaction_level      3
stress_level                 10
anxiety_level                10
addiction_level              10
depression_label              2
dtype: int64

how many uniques each column has

In [13]:
df['age'].nunique()

7

'age' has 7 uniques

In [14]:
df.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

summary statistics for numeric columns

In [15]:
for col in ["gender", "platform_usage", "social_interaction_level", "depression_label"]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- gender ---
gender
male      615
female    585
Name: count, dtype: int64

--- platform_usage ---
platform_usage
Instagram    411
TikTok       398
Both         391
Name: count, dtype: int64

--- social_interaction_level ---
social_interaction_level
medium    416
low       415
high      369
Name: count, dtype: int64

--- depression_label ---
depression_label
0    1169
1      31
Name: count, dtype: int64

In [16]:
def usage_category(hours):
    if hours < 3:
        return "Low"
    elif hours < 6:
        return "Moderate"
    else:
        return "High"
    
df["social_media_usage_group"] = df["daily_social_media_hours"].apply(usage_category)

In [17]:
df["social_media_usage_group"].value_counts()

social_media_usage_group
Moderate    518
High        351
Low         331
Name: count, dtype: int64

create categorial group for 'daily_social_media_hours'

In [18]:
df["mental_strain_score"]= df[[
    "stress_level",
    "anxiety_level",
    "addiction_level"
]].mean(axis=1)

In [19]:
df[[
    "stress_level",
    "anxiety_level",
    "addiction_level",
    "mental_strain_score"
]].describe()

       stress_level  anxiety_level  addiction_level  mental_strain_score
count   1200.000000    1200.000000      1200.000000          1200.000000
mean       5.445833       5.636667         5.565000             5.549167
std        2.903290       2.859453         2.830627             1.679376
min        1.000000       1.000000         1.000000             1.000000
25%        3.000000       3.000000         3.000000             4.333333
50%        5.000000       6.000000         6.000000             5.666667
75%        8.000000       8.000000         8.000000             6.666667
max       10.000000      10.000000        10.000000            10.000000

create 'mental_strain_score'

In [20]:
df.groupby("social_media_usage_group")[[
    "daily_social_media_hours",
    "sleep_hours",
    "screen_time_before_sleep",
    "academic_performance",
    "physical_activity",
    "stress_level",
    "anxiety_level",
    "addiction_level",
    "mental_strain_score"
]].mean().round(2)

,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,mental_strain_score
social_media_usage_group,,,,,,,,,
High,7.04,6.47,1.76,3.02,1.05,5.66,5.60,5.50,5.58
Low,1.99,6.53,1.73,3.01,1.02,5.50,5.45,5.75,5.57
Moderate,4.46,6.38,1.73,2.96,0.99,5.26,5.78,5.49,5.51

higher daily social media hours clearly does not mean worse mental strain

In [21]:
df.groupby("depression_label")[[
    "daily_social_media_hours",
    "sleep_hours",
    "screen_time_before_sleep",
    "academic_performance",
    "stress_level",
    "anxiety_level",
    "addiction_level",
]].mean()

,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,stress_level,anxiety_level,addiction_level
depression_label,,,,,,,
0,4.478785,6.494183,1.742258,2.990248,5.365269,5.557742,5.571429
1,6.719355,4.761290,1.667742,2.995484,8.483871,8.612903,5.322581

Compare average behavior and wellbeing indicators between depression label groups. 
The depression-indicator group shows higher average social media usage, lower sleep hours, and higher stress/anxiety, but the group is small, so results is biased towards total population

In [22]:
df.groupby("platform_usage")[[
    "daily_social_media_hours",
    "sleep_hours",
    "screen_time_before_sleep",
    "academic_performance",
    "physical_activity",
    "stress_level",
    "anxiety_level",
    "addiction_level",
    "mental_strain_score"
]].mean().round(2)

,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,mental_strain_score
platform_usage,,,,,,,,,
Both,4.52,6.46,1.75,2.98,1.02,5.55,5.49,5.50,5.51
Instagram,4.56,6.44,1.71,3.00,1.04,5.50,5.67,5.58,5.58
TikTok,4.53,6.45,1.76,3.00,0.98,5.29,5.75,5.62,5.55

Separating platform doesn't mean anything either, look at the mental_strain_score

In [23]:
df.groupby("social_interaction_level")[[
    "daily_social_media_hours",
    "sleep_hours",
    "screen_time_before_sleep",
    "academic_performance",
    "physical_activity",
    "stress_level",
    "anxiety_level",
    "addiction_level",
    "mental_strain_score"
]].mean().round(2)

,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,mental_strain_score
social_interaction_level,,,,,,,,,
high,4.46,6.48,1.76,2.98,1.03,5.51,5.70,5.59,5.60
low,4.54,6.46,1.73,2.99,1.00,5.35,5.53,5.47,5.45
medium,4.60,6.41,1.74,3.00,1.01,5.48,5.69,5.64,5.60

Same thing

In [24]:
numeric_cols = [
    "age",
    "daily_social_media_hours",
    "sleep_hours",
    "screen_time_before_sleep",
    "academic_performance",
    "physical_activity",
    "stress_level",
    "anxiety_level",
    "addiction_level",
    "mental_strain_score"
]

df[numeric_cols].corr().round(2)

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,mental_strain_score
age,1.00,-0.01,0.00,0.08,-0.01,0.01,-0.03,0.03,0.04,0.02
daily_social_media_hours,-0.01,1.00,-0.01,0.04,0.01,0.03,0.03,0.03,-0.02,0.02
sleep_hours,0.00,-0.01,1.00,0.01,0.02,0.01,-0.01,-0.01,-0.05,-0.04
screen_time_before_sleep,0.08,0.04,0.01,1.00,-0.03,-0.03,-0.01,-0.01,0.03,0.01
academic_performance,-0.01,0.01,0.02,-0.03,1.00,0.02,-0.00,-0.06,0.03,-0.02
physical_activity,0.01,0.03,0.01,-0.03,0.02,1.00,0.01,-0.02,0.03,0.01
stress_level,-0.03,0.03,-0.01,-0.01,-0.00,0.01,1.00,0.02,-0.00,0.59
anxiety_level,0.03,0.03,-0.01,-0.01,-0.06,-0.02,0.02,1.00,0.03,0.59
addiction_level,0.04,-0.02,-0.05,0.03,0.03,0.03,-0.00,0.03,1.00,0.58
mental_strain_score,0.02,0.02,-0.04,0.01,-0.02,0.01,0.59,0.59,0.58,1.00

Almost all correlations between behavior and lifestyle are near zero. No meaningful linear relationship

So far we have learned:

1. Different social media usage group have almost identical mental strain scores, which means daily social media duration is not a strong separator

2. Platform usage have similar mental_strain_score

3. Social interaction level groups show similar mental_strain_score

4. Correlation matrix show near no relationship

All this tells us that obvious variables are not strongly explanatory

Dashboard story:
Exploratory Dashboard of Teen Social Media Behavior and Wellbeing Indicators

This dashboard examines whether social media usage, platform choice, sleep, academic performance, and lifestyle indicators show visible patterns with mental strain. The analysis finds that most broad behavior groups are relatively similar, while the depression-indicator subgroup shows sharper difference in sleep, stress, anxiety, and usage

In [29]:
overview_metrics = {
    "total_records": len(df),
    "avg_social_media_hours": float(round(df["daily_social_media_hours"].mean(), 2)),
    "avg_sleep_hours": float(round(df["sleep_hours"].mean(), 2)),
    "avg_mental_strain_score": float(round(df["mental_strain_score"].mean(), 2)),
    "depression_indicator_rate": float(round(df["depression_label"].mean() * 100, 2))
}

overview_metrics

{'total_records': 1200,
 'avg_social_media_hours': 4.54,
 'avg_sleep_hours': 6.45,
 'avg_mental_strain_score': 5.55,
 'depression_indicator_rate': 2.58}

Usage summary:

In [30]:
usage_group_summary = df.groupby("social_media_usage_group").agg(
    records=("social_media_usage_group", "count"),
    avg_social_media_hours=("daily_social_media_hours", "mean"),
    avg_sleep_hours=("sleep_hours", "mean"),
    avg_academic_performance=("academic_performance", "mean"),
    avg_mental_strain_score=("mental_strain_score", "mean")
).round(2)

usage_group_summary

,records,avg_social_media_hours,avg_sleep_hours,avg_academic_performance,avg_mental_strain_score
social_media_usage_group,,,,,
High,351,7.04,6.47,3.02,5.58
Low,331,1.99,6.53,3.01,5.57
Moderate,518,4.46,6.38,2.96,5.51

Daily social media duration alone does not clearly separate mental strain, sleep, or academic performance in this dataset

Platform summary:

In [31]:
platform_summary = df.groupby("platform_usage").agg(
    records=("platform_usage", "count"),
    avg_social_media_hours=("daily_social_media_hours", "mean"),
    avg_sleep_hours=("sleep_hours", "mean"),
    avg_academic_performance=("academic_performance", "mean"),
    avg_mental_strain_score=("mental_strain_score", "mean")
).round(2)

platform_summary

,records,avg_social_media_hours,avg_sleep_hours,avg_academic_performance,avg_mental_strain_score
platform_usage,,,,,
Both,391,4.52,6.46,2.98,5.51
Instagram,411,4.56,6.44,3.00,5.58
TikTok,398,4.53,6.45,3.00,5.55

Platform usage also does not show a strong difference in mental strain or academic performance

mental strain score summary grouped by depression label:

In [32]:
depression_summary = df.groupby("depression_label").agg(
    records=("depression_label", "count"),
    avg_social_media_hours=("daily_social_media_hours", "mean"),
    avg_sleep_hours=("sleep_hours", "mean"),
    avg_stress_level=("stress_level", "mean"),
    avg_anxiety_level=("anxiety_level", "mean"),
    avg_addiction_level=("addiction_level", "mean"),
    avg_mental_strain_score=("mental_strain_score", "mean")
).round(2)

depression_summary

,records,avg_social_media_hours,avg_sleep_hours,avg_stress_level,avg_anxiety_level,avg_addiction_level,avg_mental_strain_score
depression_label,,,,,,,
0,1169,4.48,6.49,5.37,5.56,5.57,5.50
1,31,6.72,4.76,8.48,8.61,5.32,7.47

Broad social media behavior variables such as usage duration and platform choice show limited separation across wellbeing indicators. But the small depression-indicator subgroup shows noticeably higher strain and lower sleep, making it an interesting story for the dashboard